L=[0,1,2,0]
print('L=', L)
L.append(3)
print('L.append(3)')
print('L=', L)
L.extend(L)
print('L.extend(L)')
print('L=', L)
L.insert(0,5)
print('L.insert(0,5)')
print('L=', L)
L.remove(0)
print('L.remove(0)')
print('L=', L)
L.pop(4)
print('L.pop(4)')
print('L=', L)
L.count(1)
L.reverse()
print('L.reverse()')
print('L=', L)
L.sort()
print('L.sort()')
print('L=', L)
L.copy()
print('L.copy()')
print('L=', L)
L.clear()
print('L.clear()')
print('L=', L)

